### ISSUE TITLE
Index Error : List out of range in Line7

### ISSUE THREAD

**Issue by adityasood11** [ryanfox/visual-cryptography#1]
![image](https://user-images.githubusercontent.com/30553910/38170171-7e1be87c-359b-11e8-9b8e-045ee187db5b.png)

**Comment by ryanfox** [comment]
You need to provide an image name, e.g.

    python generate.py mysourceimage.jpg

**Comment by adityasood11** [comment]
Yes @ryanfox . That was lame from me.

**Comment by hatsat32** [comment]
fixed line should be like this

```python3
outfile = Image.new('RGB', infile1.size)
```
